exclude: '(tests/data|\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|_build|buck-out|build|dist|.*\/models\.py.*|.*\/models\/.*)'
repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.21.2
  hooks:
  - id: pyupgrade

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.10
  hooks:
    - id: ruff-check
      args: [--fix]
    - id: ruff-format
